### ISSUE TITLE
build command fails

### ISSUE THREAD

**Issue by yarelm** [uw-labs/bloomrpc#143]
I'm getting a build failure while trying to execute `yarn install && ./node_modules/.bin/electron-rebuild` on master (873953c). tried previous tagged versions and I got a similar error.

Running on Manjaro linux, node version v12.13.0

```make: *** [gpr.target.mk:193: Release/obj.target/gpr/deps/grpc/src/core/lib/gpr/log_linux.o] Error 1
make: Leaving directory '/home/yarel/Downloads/bloomrpc/app/node_modules/bloomrpc-mock/node_modules/grpc/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/yarel/Downloads/bloomrpc/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.84-1-MANJARO ```

**Comment by fenos** [comment]
you'll probably need to enable **clang** compiler in order to build the app successfully in linux
